/**
 * SomosChat Script Blockly Definitions & Generators
 * Generated by Antigravity
 */

// Initialize global mock object
var SystemMocks = {};

// Helper to fetch JSON and extend SystemMocks
function loadMocks(notify = false) {
    Promise.all([
        fetch('mock_data.json').then(res => res.json()),
        fetch('mock_scenes.json').then(res => res.json()),
        fetch('mock_human.json').then(res => res.json()),
        fetch('mock_listopc.json').then(res => res.json()),
        fetch('mock_tabelas.json').then(res => res.json()).catch(() => []),
        fetch('mock_forms.json').then(res => res.json()).catch(() => [])
    ]).then(([systemData, sceneData, humanData, listOpcData, tabelasData, formsData]) => {
        // Merge system data
        SystemMocks = Object.assign(SystemMocks, systemData);
        // Merge scene data
        SystemMocks.scene = sceneData;
        // Merge human data
        SystemMocks.human = humanData;
        // Merge list options data
        SystemMocks.listopc = listOpcData;
        // Merge tables data
        SystemMocks.tabelas = tabelasData;
        // Merge forms data
        SystemMocks.forms = formsData;
        console.log('Mocks loaded:', SystemMocks);
        if (notify) alert('Variáveis atualizadas com sucesso!');
    }).catch(err => {
        console.warn('Error loading mocks:', err);
        if (notify) alert('Erro ao atualizar variáveis: ' + err);
    });
}

// Initial load
loadMocks();

// Auto-update mocks every 60 seconds
setInterval(() => {
    loadMocks(false);
}, 60000);

// =============================================================================
// BLOCK DEFINITIONS
// =============================================================================

Blockly.defineBlocksWithJsonArray([
    // ---------------------------------------------------------------------------
    // 1. Categoria: Mensagens e Interação
    // ---------------------------------------------------------------------------
    {
        "type": "sc_msg",
        "message0": "Escrever mensagem %1",
        "args0": [
            {
                "type": "input_value",
                "name": "TEXT"
            }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 160,
        "tooltip": "Envia uma mensagem de texto.",
        "helpUrl": ""
    },
    {
        "type": "sc_msg_br",
        "message0": "Quebra de mensagem",
        "output": "Number",
        "colour": 160,
        "tooltip": "Quebra de mensagem.",
        "helpUrl": ""
    },

    {
        "type": "sc_linebreak",
        "message0": "Quebra de Linha (\\n)",
        "output": "String",
        "colour": 160,
        "tooltip": "Insere uma quebra de linha (\\n).",
        "helpUrl": ""
    },
    // sc_opc moved to manual definition below due to dynamic dropdowns

    // ---------------------------------------------------------------------------
    // 2. Categoria: Memória (Variáveis)
    // ---------------------------------------------------------------------------
    {
        "type": "sc_val_loc",
        "message0": "Localização\nDesc: %1 Lat: %2 Long: %3",
        "args0": [
            { "type": "input_value", "name": "DESC", "check": "String" },
            { "type": "input_value", "name": "LAT", "check": ["Number", "String"] },
            { "type": "input_value", "name": "LONG", "check": ["Number", "String"] }
        ],
        "inputsInline": true,
        "output": "String",
        "colour": 160,
        "tooltip": "Objeto de Localização",
        "helpUrl": ""
    },
    {
        "type": "sc_val_text_var",
        "message0": "Mensagem %1 Variável Binário %2",
        "args0": [
            { "type": "input_value", "name": "TEXT" },
            { "type": "input_value", "name": "VAR" }
        ],
        "inputsInline": true,
        "output": "String",
        "colour": 160,
        "tooltip": "Mensagem e Variável Binário para envio de arquivo",
        "helpUrl": ""
    },

    {
        "type": "sc_mem",
        "message0": "Definir variável de sessão (%) %1 o valor %2",
        "args0": [
            { "type": "input_value", "name": "KEY", "check": "String" },
            { "type": "input_value", "name": "VALUE", "check": "String" }
        ],
        "inputsInline": true,
        "previousStatement": null,
        "nextStatement": null,
        "colour": 330,
        "tooltip": "Grava na Memória de Sessão.",
        "helpUrl": ""
    },
    {
        "type": "sc_var",
        "message0": "Definir variável de cena ($) %1 o valor %2",
        "args0": [
            { "type": "input_value", "name": "KEY", "check": "String" },
            { "type": "input_value", "name": "VALUE", "check": "String" }
        ],
        "inputsInline": true,
        "previousStatement": null,
        "nextStatement": null,
        "colour": 330,
        "tooltip": "Grava na Memória de Cena.",
        "helpUrl": ""
    },
    {
        "type": "sc_clm",
        "message0": "Limpar variáveis de sessão (%)",
        "previousStatement": null,
        "nextStatement": null,
        "colour": 330,
        "tooltip": "Limpa todas as variáveis de sessão.",
        "helpUrl": ""
    },
    {
        "type": "sc_session_var",
        "message0": "%% %1 %%",
        "args0": [
            {
                "type": "field_input",
                "name": "VAR_NAME",
                "text": "nome variavel"
            }
        ],
        "output": ["String", "Number", "sc_session_var"],
        "colour": 330,
        "tooltip": "Variável de Sessão (%nome%).",
        "helpUrl": ""
    },
    {
        "type": "sc_system_var",
        "message0": "$ %1 $",
        "args0": [
            {
                "type": "field_input",
                "name": "VAR_NAME",
                "text": "nome variavel"
            }
        ],
        "output": ["String", "Number", "sc_system_var"],
        "colour": 330,
        "tooltip": "Variável de Sistema ($nome$).",
        "helpUrl": ""
    },
    {
        "type": "sc_mem_unescape",
        "message0": "Limpar texto (unescape) %% %1 %%",
        "args0": [
            {
                "type": "field_input",
                "name": "VAR_NAME",
                "text": "nome_variavel"
            }
        ],
        "output": ["String", "sc_session_var", "sc_system_var"],
        "colour": 330,
        "tooltip": "Variável de Sessão sem caracteres especiais (%var:unescape%).",
        "helpUrl": ""
    },
    {
        "type": "sc_mem_numeric",
        "message0": "Variável Fracionada %% %1 %%",
        "args0": [
            {
                "type": "field_input",
                "name": "VAR_NAME",
                "text": "nome_variavel"
            }
        ],
        "output": ["Number", "String", "sc_session_var", "sc_system_var"],
        "colour": 330,
        "tooltip": "Variável de Sessão formatada como número fracionado (%var:f%).",
        "helpUrl": ""
    },
    {
        "type": "sc_mem_money",
        "message0": "Variável Moeda %% %1 %%",
        "args0": [
            {
                "type": "field_input",
                "name": "VAR_NAME",
                "text": "nome_variavel"
            }
        ],
        "output": ["Number", "String", "sc_session_var", "sc_system_var"],
        "colour": 330,
        "tooltip": "Variável de Sessão formatada como moeda (%var:money%).",
        "helpUrl": ""
    },
    {
        "type": "sc_mem_position",
        "message0": "Pegar texto %% %1 %% na posição %2",
        "args0": [
            {
                "type": "field_input",
                "name": "VAR_NAME",
                "text": "nome_variavel"
            },
            {
                "type": "field_input",
                "name": "PARAM",
                "text": "0"
            }
        ],
        "output": ["String", "sc_session_var", "sc_system_var"],
        "colour": 330,
        "tooltip": "Variável de Sessão com Posição (%var:[n]%).",
        "helpUrl": ""
    },
    {
        "type": "sc_mem_date",
        "message0": "Obter data %% %1 %% com o formato %2",
        "args0": [
            {
                "type": "field_input",
                "name": "VAR_NAME",
                "text": "nome_variavel"
            },
            {
                "type": "field_dropdown",
                "name": "FORMAT",
                "options": [
                    ["Data (YYYYMMDD)", "data"],
                    ["Data e Hora", "datahora"],
                    ["Data ISO", "dataiso"],
                    ["Dia", "dia"],
                    ["Mês", "mes"],
                    ["Ano", "ano"],
                    ["Hora ISO (HHMM)", "horaiso"],
                    ["Hora", "hora"],
                    ["Dia da Semana", "diasemana"],
                    ["Período do Dia (1-3)", "periododia"]
                ]
            }
        ],
        "output": ["String", "sc_session_var", "sc_system_var"],
        "colour": 330,
        "tooltip": "Variável de Sessão com Formatação de Data (%var:formato%).",
        "helpUrl": ""
    },
    {
        "type": "sc_mem_json",
        "message0": "Ler JSON %% %1 %% com a propriedade %2\nsubpropriedade (opcional) %3",
        "args0": [
            {
                "type": "field_input",
                "name": "VAR_NAME",
                "text": "nome_variavel"
            },
            {
                "type": "field_input",
                "name": "PROP",
                "text": "propriedade"
            },
            {
                "type": "field_input",
                "name": "SUBPROP",
                "text": ""
            }
        ],
        "output": ["String", "sc_session_var", "sc_system_var"],
        "colour": 330,
        "tooltip": "Acessar propriedade JSON (%var@prop:subprop%).",
        "helpUrl": ""
    },

    // ---------------------------------------------------------------------------
    // 3. Categoria: Fluxo e Controle
    // ---------------------------------------------------------------------------
    {
        "type": "sc_out",
        "message0": "Ir para %2 \nEnviar mensagem (opcional): %1",
        "args0": [
            { "type": "input_value", "name": "MSG", "check": "String" },
            { "type": "input_value", "name": "ACTION", "check": "SystemRef" }
        ],
        "inputsInline": true,
        "previousStatement": null,
        "nextStatement": null,
        "colour": 290,
        "tooltip": "Saída/Roteamento.",
        "helpUrl": ""
    },
    {
        "type": "sc_sleep",
        "message0": "Pausar por %1 segundos",
        "args0": [
            { "type": "input_value", "name": "SECONDS", "check": "Number" }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 290,
        "tooltip": "Pausa a execução por N segundos (:t[n]).",
        "helpUrl": ""
    },
    {
        "type": "sc_main",
        "message0": "Início do Script %1 %2",
        "args0": [
            { "type": "input_dummy" },
            { "type": "input_statement", "name": "STACK" }
        ],
        "colour": "#4a4a4a",
        "tooltip": "Ponto de partida obrigatório do script.",
        "helpUrl": "",
        "deletable": false,
        "movable": false
    },
    {
        "type": "sc_se",
        "message0": "Se %1 Então %2",
        "args0": [
            { "type": "input_value", "name": "COND", "check": "Condition" },
            { "type": "input_statement", "name": "TRUE_ACT" }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 290,
        "tooltip": "Condicional Inline com opção Senão.",
        "helpUrl": "",
        "mutator": "sc_se_mutator",
        "extensions": ["sc_enforce_single_statement"]
    },
    // sc_ign replaced by JS definition below for mutator support

    {
        "type": "sc_lmt",
        "message0": "Checar limite da sessão",
        "previousStatement": null,
        "nextStatement": null,
        "colour": 290,
        "tooltip": "Checar limite da sessão.",
        "helpUrl": ""
    },
    {
        "type": "sc_lmt_retorno",
        "message0": "Valor do Limite de Sessão",
        "output": ["Number", "String", "sc_session_var", "sc_system_var"],
        "colour": 290,
        "tooltip": "Retorna o valor do limite de sessão ($limitesessao$).",
        "helpUrl": ""
    },
    {
        "type": "sc_mthretorno",
        "message0": "Resultado do Cálculo",
        "output": ["Number", "String", "sc_session_var", "sc_system_var"],
        "colour": 230,
        "tooltip": "Retorna o resultado do cálculo.",
        "helpUrl": ""
    },
    {
        "type": "sc_reg_erro",
        "message0": "Retorno se erro no registro",
        "output": "Number",
        "colour": 65,
        "tooltip": "Retorna o erro do registro.",
        "helpUrl": ""
    },
    {
        "type": "sc_cond",
        "message0": "%1 %2 %3",
        "args0": [
            { "type": "input_value", "name": "A" },
            {
                "type": "field_dropdown",
                "name": "OP",
                "options": [
                    ["=", "="],
                    [">", ">"],
                    [">=", ">="],
                    ["<", "<"],
                    ["<=", "<="],
                    ["<>", "<>"]
                ]
            },
            { "type": "input_value", "name": "B" }
        ],
        "inputsInline": true,
        "output": "Condition",
        "colour": 290,
        "tooltip": "Expressão Condicional",
        "helpUrl": ""
    },
    {
        "type": "sc_cond_logic",
        "message0": "%1 %2 %3",
        "args0": [
            { "type": "input_value", "name": "A", "check": "Condition" },
            {
                "type": "field_dropdown",
                "name": "OP",
                "options": [
                    ["ou", "ou"],
                    ["e", "e"]
                ]
            },
            { "type": "input_value", "name": "B", "check": "Condition" }
        ],
        "inputsInline": true,
        "output": "Condition",
        "colour": 290,
        "tooltip": "Lógica Condicional (E/OU)",
        "helpUrl": ""
    },
    {
        "type": "sc_cond_group",
        "message0": "( %1 )",
        "args0": [
            { "type": "input_value", "name": "VAL", "check": "Condition" }
        ],
        "output": "Condition",
        "colour": 290,
        "tooltip": "Agrupar condições entre parênteses",
        "helpUrl": ""
    },

    // ---------------------------------------------------------------------------
    // 4. Categoria: Manipulação de Texto e Matemática
    // ---------------------------------------------------------------------------
    {
        "type": "sc_mth",
        "message0": "Calcular %1",
        "args0": [
            { "type": "input_value", "name": "FORMULA", "check": "Number" }
        ],
        "inputsInline": true,
        "previousStatement": null,
        "nextStatement": null,
        "colour": 230,
        "tooltip": "Cálculo matemático.",
        "helpUrl": "",
        "mutator": "sc_mth_mutator"
    },
    {
        "type": "sc_math_group",
        "message0": "( %1 )",
        "args0": [
            { "type": "input_value", "name": "NUM" }
        ],
        "inputsInline": true,
        "output": "Number",
        "colour": 230,
        "tooltip": "Agrupamento com parênteses ( ).",
        "helpUrl": ""
    },
    {
        "type": "math_arithmetic",
        "message0": "%1 %2 %3",
        "args0": [
            { "type": "input_value", "name": "A", "check": ["Number", "sc_session_var", "sc_system_var"] },
            {
                "type": "field_dropdown",
                "name": "OP",
                "options": [
                    ["+", "ADD"],
                    ["-", "MINUS"],
                    ["*", "MULTIPLY"],
                    ["/", "DIVIDE"]
                ]
            },
            { "type": "input_value", "name": "B", "check": ["Number", "sc_session_var", "sc_system_var"] }
        ],
        "inputsInline": true,
        "output": "Number",
        "colour": 230,
        "tooltip": "Operação matemática (+, -, *, /).",
        "helpUrl": ""
    },
    {
        "type": "sc_len",
        "message0": "Obter quantidade de caracteres: %1",
        "args0": [
            { "type": "input_value", "name": "TEXT", "check": "String" }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 20,
        "tooltip": "Contar caracteres.",
        "helpUrl": ""
    },
    {
        "type": "sc_esq",
        "message0": "Obter os %2 primeiros caracteres do texto %1",
        "args0": [
            { "type": "input_value", "name": "TEXT" },
            { "type": "input_value", "name": "NUM", "check": "Number" }
        ],
        "inputsInline": true,
        "previousStatement": null,
        "nextStatement": null,
        "colour": 20,
        "tooltip": "Esquerda (Resultado em %var_txt_result%).",
        "helpUrl": ""
    },
    {
        "type": "sc_dir",
        "message0": "Obter os %2 últimos caracteres do texto %1",
        "args0": [
            { "type": "input_value", "name": "TEXT" },
            { "type": "input_value", "name": "NUM", "check": "Number" }
        ],
        "inputsInline": true,
        "previousStatement": null,
        "nextStatement": null,
        "colour": 20,
        "tooltip": "Direita (Resultado em %var_txt_result%).",
        "helpUrl": ""
    },
    {
        "type": "sc_sbt",
        "message0": "Obter subsequência do texto %1 Ini: %2 Num: %3",
        "args0": [
            { "type": "input_value", "name": "TEXT", "check": "String" },
            { "type": "input_value", "name": "INI", "check": ["Number", "String", "sc_session_var", "sc_system_var"] },
            { "type": "input_value", "name": "NUM", "check": ["Number", "String", "sc_session_var", "sc_system_var"] }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 20,
        "tooltip": "Subsequência (Resultado em %var_txt_result%).",
        "helpUrl": ""
    },
    {
        "type": "sc_rpl",
        "message0": "Substituir o texto %1 De: %2 Para: %3",
        "args0": [
            { "type": "input_value", "name": "TEXT", "check": "String" },
            { "type": "input_value", "name": "FROM", "check": "String" },
            { "type": "input_value", "name": "TO", "check": "String" }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 20,
        "tooltip": "Substituir (Resultado em %var_txt_result%).",
        "helpUrl": ""
    },
    {
        "type": "sc_txt_result",
        "message0": "Obter resultado do texto",
        "output": ["String", "sc_session_var", "sc_system_var"],
        "colour": 20,
        "tooltip": "Retorna o resultado da última operação de texto.",
        "helpUrl": ""
    },

    // ---------------------------------------------------------------------------
    // 5. Categoria: Dados do Usuário e Acesso
    // ---------------------------------------------------------------------------
    {
        "type": "sc_reg",
        "message0": "Registrar Usuário\nRef: %1 Ref #2 (opcional): %2",
        "args0": [
            { "type": "input_value", "name": "KEY1", "check": "String" },
            { "type": "input_value", "name": "KEY2", "check": "String" }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 65,
        "tooltip": "Registrar usuário",
        "helpUrl": ""
    },
    {
        "type": "sc_reg_var",
        "message0": "Status do registro\n Ref: %1 Ref #2 (opcional): %2",
        "args0": [
            {
                "type": "field_input",
                "name": "VAR_NAME",
                "text": "Ref"
            },
            {
                "type": "field_input",
                "name": "REF2",
                "text": ""
            }
        ],
        "output": "Number",
        "colour": 65,
        "tooltip": "Status do registro: 1 OK, 0 Offline, -1 Erro.",
        "helpUrl": ""
    },
    {
        "type": "sc_lgn",
        "message0": "Autenticar Usuário\n Ref: %1 Ref #2 (opcional): %2",
        "args0": [
            { "type": "input_value", "name": "KEY1", "check": "String" },
            { "type": "input_value", "name": "KEY2", "check": "String" }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 65,
        "tooltip": "Autenticar usuário.",
        "helpUrl": ""
    },
    {
        "type": "sc_lgf",
        "message0": "Deslogar Usuário\n Ref: %1 Ref #2 (opcional): %2",
        "args0": [
            { "type": "input_value", "name": "KEY1", "check": "String" },
            { "type": "input_value", "name": "KEY2", "check": "String" }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 65,
        "tooltip": "Logoff.",
        "helpUrl": ""
    },
    {
        "type": "sc_urg",
        "message0": "Remover Registro\n Ref: %1 Ref #2 (opcional): %2",
        "args0": [
            { "type": "input_value", "name": "KEY1", "check": "String" },
            { "type": "input_value", "name": "KEY2", "check": "String" }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 65,
        "tooltip": "Remover registro (Unregister).",
        "helpUrl": ""
    },
    {
        "type": "sc_ban",
        "message0": "Banir após %1 tentativas por %2 minutos. Ação: %3",
        "args0": [
            { "type": "input_value", "name": "TRIES", "check": ["Number", "String", "sc_session_var", "sc_system_var"] },
            { "type": "input_value", "name": "TIME", "check": ["Number", "String", "sc_session_var", "sc_system_var"] },
            { "type": "input_value", "name": "ACTION", "check": "SystemRef" }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 65,
        "tooltip": "Banir usuário temporariamente.",
        "helpUrl": ""
    },
    {
        "type": "sc_set",
        "message0": "Atualizar dado do usuário %1 como %2",
        "args0": [
            {
                "type": "field_dropdown",
                "name": "FIELD",
                "options": [
                    ["Nome", "NOME"],
                    ["Email", "EMAIL"],
                    ["Endereço", "ENDERECO"],
                    ["Bairro", "BAIRRO"],
                    ["Cidade", "CIDADE"],
                    ["UF", "UF"],
                    ["CEP", "CEP"],
                    ["CPF", "CPF"]
                ]
            },
            { "type": "input_value", "name": "VALUE", "check": "String" }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 65,
        "tooltip": "Atualizar dado do usuário.",
        "helpUrl": ""
    },
    {
        "type": "sc_get",
        "message0": "Ler dado do usuário %1 \nGuardar na variável (%) %2",
        "args0": [
            {
                "type": "field_dropdown",
                "name": "FIELD",
                "options": [
                    ["Nome", "NOME"],
                    ["Email", "EMAIL"],
                    ["Endereço", "ENDERECO"],
                    ["Bairro", "BAIRRO"],
                    ["Cidade", "CIDADE"],
                    ["UF", "UF"],
                    ["CEP", "CEP"],
                    ["CPF", "CPF"]
                ]
            },
            { "type": "input_value", "name": "VAR", "check": "String" }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 65,
        "tooltip": "Ler info do usuário para variável.",
        "helpUrl": ""
    },
    {
        "type": "sc_set_retorno",
        "message0": "Retornar confirmação de atualização",
        "output": "Number",
        "colour": 65,
        "tooltip": "Retorna a confirmação de atualização. 1 = OK, 0 = NOK",
        "helpUrl": ""
    },

    // ---------------------------------------------------------------------------
    // 6. Categoria: Ferramentas e Integrações
    // ---------------------------------------------------------------------------
    {
        "type": "sc_api",
        "message0": "Chamar API %1 em %2 Debug: %3",
        "args0": [
            {
                "type": "field_dropdown",
                "name": "METHOD",
                "options": [
                    ["GET", "GET"],
                    ["POST", "POST"],
                    ["DELETE", "DELETE"]
                ]
            },
            { "type": "input_value", "name": "URL", "check": "String" },
            { "type": "field_checkbox", "name": "DEBUG", "checked": false }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 120,
        "tooltip": "Chamada API.",
        "helpUrl": ""
    },
    {
        "type": "sc_api_auth",
        "message0": "Definir token da API: %1",
        "args0": [
            { "type": "input_value", "name": "VALUE", "check": "String" }
        ],
        "inputsInline": true,
        "previousStatement": null,
        "nextStatement": "sc_api",
        "colour": 120,
        "tooltip": "Chamada API com Autenticação.",
        "helpUrl": ""
    },
    {
        "type": "sc_api_status",
        "message0": "Status da API",
        "output": "Number",
        "colour": 120,
        "tooltip": "Retorna o status da API.",
        "helpUrl": "https://github.com/paulocorcino/SomosChat/wiki/SomosChat-Script#api"
    },
    {
        "type": "sc_api_result",
        "message0": "Retorno da API (JSON) ",
        "output": "String",
        "colour": 120,
        "tooltip": "Retorna o JSON da API.",
        "helpUrl": "https://github.com/paulocorcino/SomosChat/wiki/SomosChat-Script#api"
    },
    {
        "type": "sc_whk",
        "message0": "Enviar para webhook em %1",
        "args0": [
            { "type": "input_value", "name": "URL", "check": "String" }
        ],
        "inputsInline": true,
        "previousStatement": null,
        "nextStatement": null,
        "colour": 120,
        "tooltip": "Disparar Webhook.",
        "helpUrl": ""
    },
    {
        "type": "sc_gbn",
        "message0": "Obter arquivo da URL %1 e salvar em (%) %2",
        "args0": [
            { "type": "input_value", "name": "URL", "check": "String" },
            { "type": "input_value", "name": "MEM", "check": "String" }
        ],
        "previousStatement": null,
        "nextStatement": null,
        "colour": 120,
        "tooltip": "Obter Binário (Download arquivo).",
        "helpUrl": ""
    },
    {
        "type": "sc_pdf",
        "message0": "Gerar PDF\n Nome do Documento %2 \nConteúdo (HTML ou URL): %3\nCharset: %4\nOrientação: %5\nPapel: %6 \nGravar em (%) %1",
        "args0": [
            { "type": "input_value", "name": "MEM", "check": "String" },
            { "type": "input_value", "name": "NAME", "check": "String" },
            { "type": "input_value", "name": "SOURCE", "check": ["String", "sc_session_var", "sc_system_var"] },
            {
                "type": "field_dropdown",
                "name": "CHARSET",
                "options": [
                    ["UTF-8", "UTF-8"],
                    ["ISO-8859-1", "ISO-8859-1"]
                ]
            },
            {
                "type": "field_dropdown",
                "name": "ORIENTATION",
                "options": [
                    ["Retrato", "R"],
                    ["Paisagem", "P"]

                ]
            },
            {
                "type": "field_dropdown",
                "name": "PAPER",
                "options": [
                    ["Letter", "letter"],
                    ["A4", "a4"],
                    ["A3", "a3"]

                ]
            }
        ],
        "inputsInline": false,
        "previousStatement": null,
        "nextStatement": null,
        "colour": 120,
        "tooltip": "Gerar PDF.",
        "helpUrl": ""
    },
    {
        "type": "sc_tab_retorno",
        "message0": "Status da Gravação/Leitura (Tabela)",
        "output": "Number",
        "colour": 20,
        "tooltip": "Retorna o status da última operação em tabela ($tabretorno$). Para gravar: 1=OK, 0=Erro. Para ler: 1=Encontrado, 0=Não encontrado.",
        "helpUrl": ""
    },

    {
        "type": "sc_frm_guid",
        "message0": "Obter GUID do formulário de pesquisa",
        "output": "String",
        "colour": 20,
        "tooltip": "Obtem o GUID do formulário de pesquisa ($formguid$).",
        "helpUrl": ""
    },
    {
        "type": "sc_frm_url",
        "message0": "Obter URL do formulário de pesquisa",
        "output": "String",
        "colour": 20,
        "tooltip": "Obtem a URL do formulário de pesquisa.",
        "helpUrl": ""
    }

]);

// =============================================================================
// GENERATORS
// =============================================================================

// Helper function to handle arguments.
// If the argument comes from a variable block (sc_variable_getter), it returns it as is.
// If it's a string literal, it wraps it in quotes.
function getScArg(block, name, generator) {
    var targetBlock = block.getInputTargetBlock(name);
    var code = generator.valueToCode(block, name, generator.ORDER_NONE) || '""';

    // Clean up code if it was wrapped in parentheses by other generators
    code = code.replace(/^\((.*)\)$/, '$1');

    // Check if the target block is our variable getter
    if (targetBlock && (targetBlock.type === 'sc_session_var' || targetBlock.type === 'sc_mem_unescape' || targetBlock.type === 'sc_mem_numeric' || targetBlock.type === 'sc_mem_money' || targetBlock.type === 'sc_mem_position' || targetBlock.type === 'sc_mem_date' || targetBlock.type === 'sc_mem_json' || targetBlock.type === 'sc_system_var')) {
        // It's a variable, return as is (e.g. %nome% or $nome)
        // Remove any extra quotes if the generator added them (though valueToCode usually returns string)
        return code.replace(/^['"]|['"]$/g, '');
    }

    // If it's a raw string (e.g. "texto"), ensure it has double quotes
    // The default generator might return 'string' or "string". We want "string".
    var needsQuotes = !code.startsWith('"');

    // If it starts with % or $, it might be a simple variable or a complex expression
    if (code.startsWith('%') || code.startsWith('$')) {
        // If it contains a space or arithmetic operators, it's likely an expression that needs quotes
        if (code.includes(' ') || code.includes('+') || code.includes('-') || code.includes('*') || code.includes('/')) {
            needsQuotes = true;
        } else {
            needsQuotes = false;
        }
    }

    if (needsQuotes) {
        // If it's a number, don't quote it
        if (code !== '' && !isNaN(Number(code))) {
            return code;
        }

        // If it's not a var and not quoted, quote it.
        // However, valueToCode for strings usually returns "'text'".
        // We strip single quotes and add double quotes.
        if (code.startsWith("'") && code.endsWith("'")) {
            code = code.substring(1, code.length - 1);
        }
        return '"' + code + '"';
    }

    // If it's already double quoted, keep it.
    return code;
}

// Override the scrub_ method to use '#' for comments instead of '//'
javascript.javascriptGenerator.scrub_ = function (block, code, opt_thisOnly) {
    var commentCode = '';
    // Only collect comments for blocks that aren't inline.
    if (!block.outputConnection || !block.outputConnection.targetConnection) {
        // Collect comment for this block.
        var comment = block.getCommentText();
        if (comment) {
            comment = Blockly.utils.string.wrap(comment, this.COMMENT_WRAP - 3);
            if (block.getProcedureDef) {
                // Use a comment function for function definitions.
                commentCode += this.prefixLines(comment + '\n', '/** ', ' * ', ' */\n');
            } else {
                // - - - - MODIFIED HERE - - - -
                // Use '#' for single line comments.
                commentCode += this.prefixLines(comment + '\n', '# ');
                // - - - - - - - - - - - - - - -
            }
        }
        // Collect comments for all value arguments.
        // Don't collect comments for nested statements.
        for (var i = 0; i < block.inputList.length; i++) {
            // Blockly.inputTypes.VALUE is assumed to be 1. If inputTypes is undefined, use 1.
            if (block.inputList[i].type === (Blockly.inputTypes ? Blockly.inputTypes.VALUE : 1)) {
                var childBlock = block.inputList[i].connection.targetBlock();
                if (childBlock) {
                    var comment = this.allNestedComments(childBlock);
                    if (comment) {
                        // - - - - MODIFIED HERE - - - -
                        commentCode += this.prefixLines(comment, '# ');
                        // - - - - - - - - - - - - - - -
                    }
                }
            }
        }
    }
    var nextBlock = block.nextConnection && block.nextConnection.targetBlock();
    var nextCode = opt_thisOnly ? '' : this.blockToCode(nextBlock);
    return commentCode + code + nextCode;
};

// 1. Categoria: Mensagens e Interação
// Override standard 'text' block to encode emojis as HTML entities
javascript.javascriptGenerator.forBlock['text'] = function (block, generator) {
    var code = block.getFieldValue('TEXT');
    // Encode emojis and non-ASCII chars to HTML entities
    var result = '';
    for (var i = 0; i < code.length; i++) {
        var charCode = code.codePointAt(i);
        if (charCode > 127) {
            result += '&#' + charCode + ';';
            // If surrogate pair, skip next code unit
            if (charCode > 0xFFFF) {
                i++;
            }
        } else {
            result += code[i];
        }
    }
    return ['"' + result + '"', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_linebreak'] = function (block, generator) {
    return ['"\\n"', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_msg_br'] = function (block, generator) {
    return ['"#br"', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_sleep'] = function (block, generator) {
    var seconds = generator.valueToCode(block, 'SECONDS', generator.ORDER_NONE) || '1';
    return '::msg("#t' + seconds + '")\n';
};

javascript.javascriptGenerator.forBlock['sc_msg'] = function (block, generator) {
    var text = getScArg(block, 'TEXT', generator);
    return '::msg(' + text + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_opc'] = function (block, generator) {
    var mem = block.getFieldValue('MEM');
    var listCode = block.getFieldValue('LIST_CODE');
    var gotoScene = block.getFieldValue('GOTO');
    var order = block.getFieldValue('ORDER');
    var typeOp = block.getFieldValue('TYPE_OP');
    var format = block.getFieldValue('FORMAT');
    var separator = block.getFieldValue('SEPARATOR');
    var extraOp = getScArg(block, 'EXTRA_OP', generator);
    var extraGoto = block.getFieldValue('EXTRA_GOTO');

    // ::opc(mem, list, goto, order, type, format, sep, extra_op, extra_goto)
    var args = [
        '"' + mem + '"',
        '"' + listCode + '"',
        (gotoScene ? '"' + gotoScene + '"' : '""'),
        order,
        typeOp,
        '"' + format + '"',
        separator
    ];

    // Optional args handling
    if (extraOp && extraOp !== '""') {
        args.push(extraOp);
        if (extraGoto && extraGoto !== '') {
            args.push('"' + extraGoto + '"');
        }
    } else if (extraGoto && extraGoto !== '') {
        // If extraOp is empty but extraGoto is set, we might need a placeholder or logic.
        // Assuming extraGoto usually depends on extraOp.
        // If the user wants just a go-to without extra op text, it might be weird.
        // Generating empty string for extraOp to reach extraGoto position
        args.push('""');
        args.push('"' + extraGoto + '"');
    }

    return '::opc(' + args.join(', ') + ')\n';
};

// 2. Categoria: Memória (Variáveis)
javascript.javascriptGenerator.forBlock['sc_val_loc'] = function (block, generator) {
    var desc = getScArg(block, 'DESC', generator);
    var lat = getScArg(block, 'LAT', generator);
    var long = getScArg(block, 'LONG', generator);
    // Returns arguments directly to be wrapped by ::msg()
    return [desc + ', ' + lat + ', ' + long, generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_val_text_var'] = function (block, generator) {
    var text = getScArg(block, 'TEXT', generator);
    var variable = getScArg(block, 'VAR', generator);
    // Returns comma separated: "Text", %Var%
    return [text + ', ' + variable, generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_mem'] = function (block, generator) {
    var key = getScArg(block, 'KEY', generator);
    var val = getScArg(block, 'VALUE', generator);
    return '::mem(' + key + ', ' + val + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_var'] = function (block, generator) {
    var key = getScArg(block, 'KEY', generator);
    var val = getScArg(block, 'VALUE', generator);
    return '::var(' + key + ', ' + val + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_clm'] = function (block, generator) {
    return '::clm()\n';
};

javascript.javascriptGenerator.forBlock['sc_session_var'] = function (block, generator) {
    var varName = block.getFieldValue('VAR_NAME');
    // Wrap in %...%
    return ['%' + varName + '%', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_api_status'] = function (block, generator) {
    return ['$api_status$', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_api_result'] = function (block, generator) {
    return ['%api_retorno%', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_reg_var'] = function (block, generator) {
    var varName = block.getFieldValue('VAR_NAME');
    var ref2 = block.getFieldValue('REF2');

    if (ref2 && ref2.trim() !== "") {
        return ['%' + ref2 + '_' + varName + '%', generator.ORDER_ATOMIC];
    }
    // Warp in %login_...%
    return ['%login_' + varName + '%', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_system_var'] = function (block, generator) {
    var varName = block.getFieldValue('VAR_NAME');
    // Wrap in $...$
    return ['$' + varName + '$', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_mem_unescape'] = function (block, generator) {
    var varName = block.getFieldValue('VAR_NAME');
    return ['%' + varName + ':unescape%', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_mem_numeric'] = function (block, generator) {
    var varName = block.getFieldValue('VAR_NAME');
    return ['%' + varName + ':f%', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_mem_money'] = function (block, generator) {
    var varName = block.getFieldValue('VAR_NAME');
    return ['%' + varName + ':money%', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_mem_position'] = function (block, generator) {
    var varName = block.getFieldValue('VAR_NAME');
    var param = block.getFieldValue('PARAM');
    return ['%' + varName + ':' + param + '%', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_mem_date'] = function (block, generator) {
    var varName = block.getFieldValue('VAR_NAME');
    var format = block.getFieldValue('FORMAT');
    return ['%' + varName + ':' + format + '%', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_mem_json'] = function (block, generator) {
    var varName = block.getFieldValue('VAR_NAME');
    var prop = block.getFieldValue('PROP');
    var subprop = block.getFieldValue('SUBPROP');

    if (subprop && subprop.trim() !== "") {
        return ['%' + varName + '@' + prop + ':' + subprop + '%', generator.ORDER_ATOMIC];
    }
    return ['%' + varName + '@' + prop + '%', generator.ORDER_ATOMIC];
};

// =============================================================================
// Generators
// =============================================================================

javascript.javascriptGenerator.forBlock['sc_main'] = function (block, generator) {
    var branch = generator.statementToCode(block, 'STACK');
    if (block.disabled) {
        return '';
    }
    return branch;
};

// 3. Categoria: Fluxo e Controle
javascript.javascriptGenerator.forBlock['sc_out'] = function (block, generator) {
    var msg = getScArg(block, 'MSG', generator);
    var action = generator.valueToCode(block, 'ACTION', generator.ORDER_NONE) || '""';
    return '::out(' + msg + ', ' + action + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_se'] = function (block, generator) {
    var cond = generator.valueToCode(block, 'COND', generator.ORDER_NONE) || '""';
    var trueAct = generator.statementToCode(block, 'TRUE_ACT').trim();

    var falseAct = '';
    if (block.getInput('FALSE_ACT')) {
        falseAct = generator.statementToCode(block, 'FALSE_ACT').trim();
    }

    // ::se(condicao ? verdadeiro ; falso)
    // If falseAct is empty, omit the separator
    if (!falseAct) {
        return '::se(' + cond + ' ? ' + trueAct + ')\n';
    }
    return '::se(' + cond + ' ? ' + trueAct + ' ; ' + falseAct + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_ign'] = function (block, generator) {
    var elements = [];
    var count = block.itemCount_ || 0;
    // Fallback if itemCount_ is undefined but has old static inputs?
    // The new block definition uses itemCount_, old blocks might need migration or just rely on 0 defaults if opened in new editor.
    // Actually, distinct blocks. New instance will have itemCount_.
    for (var i = 0; i < count; i++) {
        var arg = getScArg(block, 'VAL' + i, generator);
        elements.push(arg);
    }
    return '::ign(' + elements.join(', ') + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_lmt'] = function (block, generator) {
    return '::lmt()\n';
};

javascript.javascriptGenerator.forBlock['sc_lmt_retorno'] = function (block, generator) {
    return ['$limitesessao$', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_mthretorno'] = function (block, generator) {
    // Returns a system variable, so it should be an output block
    return ['$mthretorno$', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_reg_erro'] = function (block, generator) {
    // Returns a system variable, so it should be an output block
    return ['$reg_erro$', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_cond'] = function (block, generator) {
    var a = generator.valueToCode(block, 'A', generator.ORDER_NONE) || '';
    var b = generator.valueToCode(block, 'B', generator.ORDER_NONE) || '';
    var op = block.getFieldValue('OP');
    // Ensure spaces around operator
    var code = a + ' ' + op + ' ' + b;
    return [code, generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_cond_logic'] = function (block, generator) {
    var a = generator.valueToCode(block, 'A', generator.ORDER_NONE) || '';
    var b = generator.valueToCode(block, 'B', generator.ORDER_NONE) || '';
    var op = block.getFieldValue('OP');
    // Ensure spaces around operator
    var code = a + ' ' + op + ' ' + b;
    return [code, generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_cond_group'] = function (block, generator) {
    var val = generator.valueToCode(block, 'VAL', generator.ORDER_NONE) || '""';
    var code = '(' + val + ')';
    return [code, generator.ORDER_ATOMIC];
};

// 4. Categoria: Manipulação de Texto e Matemática
javascript.javascriptGenerator.forBlock['sc_mth'] = function (block, generator) {
    var formula = getScArg(block, 'FORMULA', generator);
    var varName = block.getFieldValue('VAR_NAME');

    // If formula is empty string or quoted empty string, just generate ::mth()
    if (!formula || formula === '""' || formula === "''") {
        return '::mth()\n';
    }

    // ::mth(formula, varname)
    if (block.hasVar_ && varName && varName !== '""' && varName !== "''") {
        return '::mth(' + formula + ', "' + varName + '")\n';
    }

    return '::mth(' + formula + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_math_group'] = function (block, generator) {
    var value = generator.valueToCode(block, 'NUM', generator.ORDER_NONE) || '';
    return ['(' + value + ')', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['math_arithmetic'] = function (block, generator) {
    // Standard operators
    var OPERATORS = {
        'ADD': [' + ', generator.ORDER_ADDITION],
        'MINUS': [' - ', generator.ORDER_SUBTRACTION],
        'MULTIPLY': [' * ', generator.ORDER_MULTIPLICATION],
        'DIVIDE': [' / ', generator.ORDER_DIVISION],
    };

    var targetA = block.getInputTargetBlock('A');
    var targetB = block.getInputTargetBlock('B');

    // If either side is NULL (not connected), return empty string so sc_mth can handle it
    if (!targetA || !targetB) {
        return ['', generator.ORDER_ATOMIC];
    }

    var opValue = block.getFieldValue('OP');
    var tuple = OPERATORS[opValue];
    var operator = tuple[0];
    var order = tuple[1];

    var argument0 = getScArg(block, 'A', generator);
    var argument1 = getScArg(block, 'B', generator);

    var code = argument0 + operator + argument1;
    return [code, order];
};

javascript.javascriptGenerator.forBlock['sc_len'] = function (block, generator) {
    var text = getScArg(block, 'TEXT', generator);
    return '::len("var_txt_result", ' + text + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_esq'] = function (block, generator) {
    var text = getScArg(block, 'TEXT', generator);
    var num = getScArg(block, 'NUM', generator);
    return '::esq("var_txt_result", ' + text + ', ' + num + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_dir'] = function (block, generator) {
    var text = getScArg(block, 'TEXT', generator);
    var num = getScArg(block, 'NUM', generator);
    return '::dir("var_txt_result", ' + text + ', ' + num + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_sbt'] = function (block, generator) {
    var text = getScArg(block, 'TEXT', generator);
    var ini = getScArg(block, 'INI', generator);
    var num = getScArg(block, 'NUM', generator);
    return '::sbt("var_txt_result", ' + text + ', ' + ini + ', ' + num + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_rpl'] = function (block, generator) {
    var text = getScArg(block, 'TEXT', generator);
    var from = getScArg(block, 'FROM', generator);
    var to = getScArg(block, 'TO', generator);
    return '::rpl("var_txt_result", ' + text + ', ' + from + ', ' + to + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_txt_result'] = function (block, generator) {
    return ['%var_txt_result%', generator.ORDER_ATOMIC];
};

// 5. Categoria: Dados do Usuário e Acesso
javascript.javascriptGenerator.forBlock['sc_reg'] = function (block, generator) {
    var key1 = getScArg(block, 'KEY1', generator);
    var key2 = getScArg(block, 'KEY2', generator);

    if (!key2 || key2 === '""') {
        return '::reg(' + key1 + ')\n';
    }
    return '::reg(' + key1 + ', ' + key2 + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_lgn'] = function (block, generator) {
    var key1 = getScArg(block, 'KEY1', generator);
    var key2 = getScArg(block, 'KEY2', generator);

    if (!key2 || key2 === '""') {
        return '::lgn(' + key1 + ')\n';
    }
    return '::lgn(' + key1 + ', ' + key2 + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_lgf'] = function (block, generator) {
    var key1 = getScArg(block, 'KEY1', generator);
    var key2 = getScArg(block, 'KEY2', generator);

    if (!key2 || key2 === '""') {
        return '::lgf(' + key1 + ')\n';
    }
    return '::lgf(' + key1 + ', ' + key2 + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_urg'] = function (block, generator) {
    var key1 = getScArg(block, 'KEY1', generator);
    var key2 = getScArg(block, 'KEY2', generator);

    if (!key2 || key2 === '""') {
        return '::urg(' + key1 + ')\n';
    }
    return '::urg(' + key1 + ', ' + key2 + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_ban'] = function (block, generator) {
    var tries = getScArg(block, 'TRIES', generator);
    var time = getScArg(block, 'TIME', generator);
    var action = generator.valueToCode(block, 'ACTION', generator.ORDER_NONE) || '"{end}"';
    return '::ban(' + tries + ', ' + time + ', ' + action + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_set'] = function (block, generator) {
    var field = block.getFieldValue('FIELD');
    var value = getScArg(block, 'VALUE', generator);
    // Field is a string literal from dropdown, so wrap in quotes
    return '::set("' + field + '", ' + value + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_set_retorno'] = function (block, generator) {
    return ['$set_retorno$', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_frm_guid'] = function (block, generator) {
    return ['$formguid$', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_tab_retorno'] = function (block, generator) {
    return ['$tabretorno$', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_frm_url'] = function (block, generator) {
    return ['$formurl$', generator.ORDER_ATOMIC];
};

javascript.javascriptGenerator.forBlock['sc_get'] = function (block, generator) {
    var field = block.getFieldValue('FIELD');
    var variable = getScArg(block, 'VAR', generator);
    return '::get("' + field + '", ' + variable + ')\n';
};

// 6. Categoria: Ferramentas e Integrações
javascript.javascriptGenerator.forBlock['sc_api'] = function (block, generator) {
    var method = block.getFieldValue('METHOD');
    var url = getScArg(block, 'URL', generator);
    var debug = block.getFieldValue('DEBUG') === 'TRUE';

    if (debug) {
        return '::api("' + method + '", ' + url + ', "debug")\n';
    }
    return '::api("' + method + '", ' + url + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_api_auth'] = function (block, generator) {
    var method = "authorization";
    var value = getScArg(block, 'VALUE', generator);
    return '::api("' + method + '", ' + value + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_whk'] = function (block, generator) {
    var url = getScArg(block, 'URL', generator);
    return '::whk(' + url + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_gbn'] = function (block, generator) {
    var mem = getScArg(block, 'MEM', generator);
    var url = getScArg(block, 'URL', generator);
    return '::gbn(' + mem + ', ' + url + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_pdf'] = function (block, generator) {
    var mem = getScArg(block, 'MEM', generator);
    var name = getScArg(block, 'NAME', generator);
    var source = getScArg(block, 'SOURCE', generator);
    var charset = block.getFieldValue('CHARSET');
    var orientation = block.getFieldValue('ORIENTATION');
    var paper = block.getFieldValue('PAPER');
    return '::pdf(' + mem + ', ' + name + ', ' + source + ', "' + charset + '", "' + orientation + '", "' + paper + '")\n';
};

javascript.javascriptGenerator.forBlock['sc_tab'] = function (block, generator) {
    var tableId = block.getFieldValue('TABLE_ID');
    var id = getScArg(block, 'ID', generator);
    var url = getScArg(block, 'URL', generator);

    // ::tab(table_id, id, url)
    // If url is "" or '"', it's optional, but function signature usually expects 3 args if using url.
    // Making it clear in the output.
    return '::tab("' + tableId + '", ' + id + ', ' + url + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_gtb'] = function (block, generator) {
    var tableId = block.getFieldValue('TABLE_ID');
    var id = getScArg(block, 'ID', generator);
    var variable = getScArg(block, 'VAR', generator);

    // ::gtb(table_id, id, variable)
    return '::gtb("' + tableId + '", ' + id + ', ' + variable + ')\n';
};

javascript.javascriptGenerator.forBlock['sc_frm'] = function (block, generator) {
    var formId = block.getFieldValue('FORM_ID');

    // ::frm("form_id")
    return '::frm("' + formId + '")\n';
};

// =============================================================================
// SYSTEM TEMPLATE VARIABLES (Dynamic Dropdowns)
// =============================================================================

/**
 * Helper to get options from the global SystemMocks object.
 * @param {string} key The key in SystemMocks (e.g., 'msg', 'arq').
 * @returns {Array} Array of [Description, ID] pairs.
 */
function getSysOptions(key) {
    // Check if SystemMocks is defined (it should be loaded from mock_data.js)
    if (typeof SystemMocks === 'undefined' || !SystemMocks[key]) {
        return [['Carregando...', '']];
    }
    return SystemMocks[key].map(function (item) {
        var desc = item.desc || item.Tabela || item.Form || item.id || "Sem nome";
        var id = item.id || item.ID || "";
        return [desc, id];
    });
}

// Configuration for the system blocks
var sysBlocks = [
    { type: 'sc_sys_msg', key: 'msg', title: 'Modelo Msg', prefix: '@@msg', color: 180 },
    { type: 'sc_sys_arq', key: 'arq', title: 'Arquivo', prefix: '@@arq', color: 180 },
    { type: 'sc_sys_img', key: 'img', title: 'Imagem', prefix: '@@img', color: 180 },
    { type: 'sc_sys_aud', key: 'aud', title: 'Audio', prefix: '@@aud', color: 180 },
    { type: 'sc_sys_gim', key: 'gim', title: 'Grupo Img', prefix: '@@gim', color: 180 },
    { type: 'sc_sys_gaq', key: 'gaq', title: 'Grupo Arq', prefix: '@@gaq', color: 180 },
    { type: 'sc_sys_vcd', key: 'vcd', title: 'V-Card', prefix: '@@vcd', color: 180 },
    { type: 'sc_sys_vsys', key: 'vsys', title: 'Variável Sessão Padrão', prefix: '', color: 330, raw: true, outputType: ["SystemRef", "String"] },
    { type: 'sc_sys_vmem', key: 'vmem', title: 'Variável Memória Padrão', prefix: '', color: 330, raw: true, outputType: ["SystemRef", "String"] },
    { type: 'sc_sys_scene', key: 'scene', title: 'Cena:', prefix: '', color: 290, raw: true, outputType: ["SystemRef", "String"] },
    { type: 'sc_sys_human', key: 'human', title: 'Atendimento:', prefix: '', color: 290, raw: true, outputType: ["SystemRef", "String"] }
];

// Manual Definition for sc_opc to support dynamic dropdowns
Blockly.Blocks['sc_frm'] = {
    init: function () {
        this.appendDummyInput()
            .appendField("Iniciar formulário:")
            .appendField(new Blockly.FieldDropdown(function () {
                return getSysOptions('forms');
            }), "FORM_ID");
        this.setPreviousStatement(true, null);
        this.setNextStatement(true, null);
        this.setColour(20);
        this.setTooltip("Gera links únicos para formulários externos.");
        this.setHelpUrl("");
    }
};

Blockly.Blocks['sc_tab'] = {
    init: function () {
        this.appendDummyInput()
            .appendField("Gravar na Tabela:")
            .appendField(new Blockly.FieldDropdown(function () {
                return getSysOptions('tabelas');
            }), "TABLE_ID");
        this.appendValueInput("ID")
            .setCheck(["String", "Number", "sc_session_var", "sc_system_var"])
            .appendField("Identificador do registro:");
        this.appendValueInput("URL")
            .setCheck(["String", "sc_session_var", "sc_system_var"])
            .appendField("URL Externa (Opcional):");
        this.setPreviousStatement(true, null);
        this.setNextStatement(true, null);
        this.setInputsInline(false);
        this.setColour(20);
        this.setTooltip("Grava informações em uma tabela do sistema.");
        this.setHelpUrl("");
    }
};

Blockly.Blocks['sc_gtb'] = {
    init: function () {
        this.appendDummyInput()
            .appendField("Ler da Tabela:")
            .appendField(new Blockly.FieldDropdown(function () {
                return getSysOptions('tabelas');
            }), "TABLE_ID");
        this.appendValueInput("ID")
            .setCheck(["String", "Number", "sc_session_var", "sc_system_var"])
            .appendField("Identificador do registro:");
        this.appendValueInput("VAR")
            .setCheck(["String", "sc_session_var"])
            .appendField("Nome da variável (%):");
        this.setPreviousStatement(true, null);
        this.setNextStatement(true, null);
        this.setInputsInline(false);
        this.setColour(20);
        this.setTooltip("Recupera dados (JSON) de uma tabela do sistema.");
        this.setHelpUrl("");
    }
};

Blockly.Blocks['sc_opc'] = {
    init: function () {
        this.appendDummyInput()
            .appendField("Menu de Opções");
        this.appendDummyInput()
            .appendField("Gravar em (%):")
            .appendField(new Blockly.FieldTextInput("menu_escolha"), "MEM")
            .appendField("Lista:")
            .appendField(new Blockly.FieldDropdown(function () {
                return getSysOptions('listopc');
            }), "LIST_CODE");
        this.appendDummyInput()
            .appendField("Ir para:")
            .appendField(new Blockly.FieldDropdown(function () {
                return getSysOptions('scene');
            }), "GOTO");
        this.appendDummyInput()
            .appendField("Ordem:")
            .appendField(new Blockly.FieldDropdown([
                ["Crescente", "0"],
                ["Decrescente", "1"],
                ["Aleatório", "2"]
            ]), "ORDER")
            .appendField("Tipo:")
            .appendField(new Blockly.FieldDropdown([
                ["Numérico (1-n)", "0"],
                ["Nome da Opção", "1"]
            ]), "TYPE_OP");
        this.appendDummyInput()
            .appendField("Formato:")
            .appendField(new Blockly.FieldTextInput(":op - :txt"), "FORMAT")
            .appendField("Separador:")
            .appendField(new Blockly.FieldDropdown([
                ["Quebra de Linha", "0"],
                ["Espaço", "1"],
                ["Vírgula", "2"]
            ]), "SEPARATOR");
        this.appendValueInput("EXTRA_OP")
            .setCheck(["String", "sc_session_var", "sc_system_var"])
            .appendField("Opção Extra:");
        this.appendDummyInput()
            .appendField("Ir para Extra (Opcional):")
            .appendField(new Blockly.FieldDropdown(function () {
                var options = getSysOptions('scene');
                // Create a copy to not mutate the cached mocks if getSysOptions returns ref (it maps, so new array)
                // Add an empty option at the top
                var emptyOpt = ["(Vazio)", ""];
                // We cannot unshift to the result of getSysOptions inside the closure easily without recreating the array every time.
                // getSysOptions returns a new array of arrays.
                return [emptyOpt].concat(options);
            }), "EXTRA_GOTO");

        this.setPreviousStatement(true, null);
        this.setNextStatement(true, null);
        this.setColour(160);
        this.setTooltip("Menu de Opções Dinâmico");
    }
};

// Register Blocks and Generators
sysBlocks.forEach(function (conf) {
    // Block Definition
    Blockly.Blocks[conf.type] = {
        init: function () {
            this.appendDummyInput()
                .appendField(conf.title)
                .appendField(new Blockly.FieldDropdown(function () {
                    return getSysOptions(conf.key);
                }), "ID");
            this.setOutput(true, conf.outputType || "String");
            this.setColour(conf.color);
            this.setTooltip(conf.title + " (" + conf.prefix + "[id])");
        }
    };

    // Generator
    javascript.javascriptGenerator.forBlock[conf.type] = function (block, generator) {
        var id = block.getFieldValue('ID');
        var code = (conf.raw) ? id : conf.prefix + '[' + id + ']';
        // Return as string
        return [code, generator.ORDER_ATOMIC];
    };
});

// =============================================================================
// OVERRIDES
// =============================================================================

// Override standard text_join to produce concatenated string literal: "Part1Part2"
javascript.javascriptGenerator.forBlock['text_join'] = function (block, generator) {
    var elements = [];
    for (var i = 0; i < block.itemCount_; i++) {
        var code = generator.valueToCode(block, 'ADD' + i, generator.ORDER_NONE) || '';
        // If code is quoted string '"text"', strip quotes
        if (code.startsWith('"') && code.endsWith('"')) {
            code = code.substring(1, code.length - 1);
        } else if (code.startsWith("'") && code.endsWith("'")) {
            code = code.substring(1, code.length - 1);
        }
        elements.push(code);
    }
    // Join all parts and wrap in double quotes
    var code = '"' + elements.join('') + '"';
    return [code, generator.ORDER_ATOMIC];
};

// Block Definition for sc_sys_action
Blockly.Blocks['sc_sys_action'] = {
    init: function () {
        this.appendDummyInput()
            .appendField("Ação:")
            .appendField(new Blockly.FieldDropdown([
                ["Continuar fluxo", "{true}"],
                ["Repetir pergunta / pedir de novo", "{false}"],
                ["Encerrar conversa", "{end}"]
            ]), "ACTION");
        this.setOutput(true, ["SystemRef", "String"]);
        this.setColour(290);
        this.setTooltip("Ações de controle de fluxo");
    }
};

javascript.javascriptGenerator.forBlock['sc_sys_action'] = function (block, generator) {
    var action = block.getFieldValue('ACTION');
    return [action, generator.ORDER_ATOMIC];
};

// =============================================================================
// Mutator Definition for sc_ign
// =============================================================================

Blockly.Blocks['sc_ign_container'] = {
    init: function () {
        this.setColour(290);
        this.appendDummyInput()
            .appendField("Ignorar");
        this.appendStatementInput("STACK");
        this.setTooltip("Adicionar ou remover valores para ignorar.");
        this.contextMenu = false;
    }
};

Blockly.Blocks['sc_ign_item'] = {
    init: function () {
        this.setColour(290);
        this.appendDummyInput()
            .appendField("Valor");
        this.setPreviousStatement(true);
        this.setNextStatement(true);
        this.setTooltip("Valor a ser ignorado.");
        this.contextMenu = false;
    }
};

// Mixin object for the mutator
var SC_IGN_MUTATOR_MIXIN = {
    mutationToDom: function () {
        var container = Blockly.utils.xml.createElement('mutation');
        container.setAttribute('items', this.itemCount_);
        return container;
    },
    domToMutation: function (xmlElement) {
        this.itemCount_ = parseInt(xmlElement.getAttribute('items'), 10);
        this.updateShape_();
    },
    decompose: function (workspace) {
        var containerBlock = workspace.newBlock('sc_ign_container');
        containerBlock.initSvg();
        var connection = containerBlock.getInput('STACK').connection;
        for (var i = 0; i < this.itemCount_; i++) {
            var itemBlock = workspace.newBlock('sc_ign_item');
            itemBlock.initSvg();
            connection.connect(itemBlock.previousConnection);
            connection = itemBlock.nextConnection;
        }
        return containerBlock;
    },
    compose: function (containerBlock) {
        var itemBlock = containerBlock.getInputTargetBlock('STACK');
        var connections = [];
        while (itemBlock) {
            connections.push(itemBlock.valueConnection_);
            itemBlock = itemBlock.nextConnection && itemBlock.nextConnection.targetBlock();
        }
        for (var i = 0; i < this.itemCount_; i++) {
            var connection = this.getInput('VAL' + i).connection.targetConnection;
            if (connection && connections.indexOf(connection) == -1) {
                connection.disconnect();
            }
        }
        this.itemCount_ = connections.length;
        this.updateShape_();
        for (var i = 0; i < this.itemCount_; i++) {
            if (connections[i]) {
                this.getInput('VAL' + i).connection.connect(connections[i]);
            }
        }
    },
    saveConnections: function (containerBlock) {
        var itemBlock = containerBlock.getInputTargetBlock('STACK');
        var i = 0;
        while (itemBlock) {
            var input = this.getInput('VAL' + i);
            itemBlock.valueConnection_ = input && input.connection.targetConnection;
            i++;
            itemBlock = itemBlock.nextConnection && itemBlock.nextConnection.targetBlock();
        }
    },
    updateShape_: function () {
        // Delete everything.
        if (this.getInput('EMPTY')) {
            this.removeInput('EMPTY');
        }
        var i = 0;
        while (this.getInput('VAL' + i)) {
            this.removeInput('VAL' + i);
            i++;
        }
        // Rebuild.
        if (this.itemCount_ == 0) {
            this.appendDummyInput('EMPTY')
                .appendField("Nenhum valor");
        } else {
            for (var i = 0; i < this.itemCount_; i++) {
                var input = this.appendValueInput('VAL' + i)
                    .setCheck(['String', 'Number', 'sc_session_var', 'sc_system_var']);
            }
        }
    }
};

// Register the mutator extension
Blockly.Extensions.registerMutator(
    'sc_ign_mutator',
    SC_IGN_MUTATOR_MIXIN,
    function () {
        // Helper function (Init)
        this.itemCount_ = 2;
        this.updateShape_();
    },
    ['sc_ign_item']
);

Blockly.Blocks['sc_ign'] = {
    init: function () {
        this.jsonInit({
            "type": "sc_ign",
            "message0": "Ignorar estas entradas na validação: %1",
            "args0": [
                {
                    "type": "field_label"
                }
            ],
            "previousStatement": null,
            "nextStatement": null,
            "colour": 290,
            "tooltip": "Ignorar valores durante a validação.",
            "mutator": "sc_ign_mutator"
        });
    }
};
// =============================================================================
// Mutator Definition for sc_se (If/Else)
// =============================================================================

Blockly.Blocks['sc_se_mutator_container'] = {
    init: function () {
        this.setColour(290);
        this.appendDummyInput()
            .appendField("Se");
        this.appendStatementInput('STACK');
        this.setTooltip("Adicionar 'Senão' ao bloco");
        this.contextMenu = false;
    }
};

Blockly.Blocks['sc_se_mutator_else'] = {
    init: function () {
        this.setColour(290);
        this.appendDummyInput()
            .appendField("Senão");
        this.setPreviousStatement(true);
        this.setTooltip("Adiciona uma condição 'Senão'");
        this.contextMenu = false;
    }
};

var SC_SE_MUTATOR_MIXIN = {
    mutationToDom: function () {
        var container = Blockly.utils.xml.createElement('mutation');
        if (this.hasElse_) {
            container.setAttribute('else', 1);
        }
        return container;
    },
    domToMutation: function (xmlElement) {
        this.hasElse_ = parseInt(xmlElement.getAttribute('else'), 10) == 1;
        this.updateShape_();
    },
    decompose: function (workspace) {
        var containerBlock = workspace.newBlock('sc_se_mutator_container');
        containerBlock.initSvg();
        var connection = containerBlock.getInput('STACK').connection;
        if (this.hasElse_) {
            var elseBlock = workspace.newBlock('sc_se_mutator_else');
            elseBlock.initSvg();
            connection.connect(elseBlock.previousConnection);
        }
        return containerBlock;
    },
    compose: function (containerBlock) {
        var clauseBlock = containerBlock.getInputTargetBlock('STACK');
        this.hasElse_ = false;
        var elseStatementConnection = null;
        while (clauseBlock) {
            if (clauseBlock.type == 'sc_se_mutator_else') {
                this.hasElse_ = true;
                elseStatementConnection = clauseBlock.valueConnection_;
            }
            clauseBlock = clauseBlock.nextConnection && clauseBlock.nextConnection.targetBlock();
        }
        this.updateShape_();
        // Reconnect if needed
        if (this.hasElse_ && elseStatementConnection) {
            var input = this.getInput('FALSE_ACT');
            if (input && input.connection) {
                input.connection.connect(elseStatementConnection);
            }
        }
    },
    saveConnections: function (containerBlock) {
        var clauseBlock = containerBlock.getInputTargetBlock('STACK');
        while (clauseBlock) {
            if (clauseBlock.type == 'sc_se_mutator_else') {
                var inputElse = this.getInput('FALSE_ACT');
                clauseBlock.valueConnection_ = inputElse && inputElse.connection.targetConnection;
            }
            clauseBlock = clauseBlock.nextConnection && clauseBlock.nextConnection.targetBlock();
        }
    },
    updateShape_: function () {
        if (this.hasElse_) {
            if (!this.getInput('FALSE_ACT')) {
                this.appendStatementInput('FALSE_ACT')
                    .appendField("Senão");
            }
        } else {
            if (this.getInput('FALSE_ACT')) {
                this.removeInput('FALSE_ACT');
            }
        }
    }
};

Blockly.Extensions.registerMutator(
    'sc_se_mutator',
    SC_SE_MUTATOR_MIXIN,
    function () {
        this.hasElse_ = false;
    },
    ['sc_se_mutator_else']
);

// =============================================================================
// Extensions
// =============================================================================

Blockly.Extensions.register('sc_enforce_single_statement', function () {
    this.setOnChange(function (e) {
        if (this.workspace.isDragging && this.workspace.isDragging()) {
            return;
        }
        var enforceSingle = function (block, inputName) {
            if (!block.getInput(inputName)) return; // Safety check
            var first = block.getInputTargetBlock(inputName);
            if (first && first.getNextBlock()) {
                var next = first.getNextBlock();
                next.unplug(true);
            }
        };
        enforceSingle(this, 'TRUE_ACT');
        enforceSingle(this, 'FALSE_ACT');
    });
});
// =============================================================================
// Mutator Definition for sc_mth (Calcular)
// =============================================================================

Blockly.Blocks['sc_mth_mutator_container'] = {
    init: function () {
        this.setColour(230);
        this.appendDummyInput()
            .appendField("Calcular");
        this.appendStatementInput('STACK');
        this.setTooltip("Adicionar campo de variável de retorno.");
        this.contextMenu = false;
    }
};

Blockly.Blocks['sc_mth_mutator_var'] = {
    init: function () {
        this.setColour(230);
        this.appendDummyInput()
            .appendField("Variável de Retorno");
        this.setPreviousStatement(true);
        this.setTooltip("Adiciona o campo para definir a variável de retorno.");
        this.contextMenu = false;
    }
};

var SC_MTH_MUTATOR_MIXIN = {
    mutationToDom: function () {
        var container = Blockly.utils.xml.createElement('mutation');
        if (this.hasVar_) {
            container.setAttribute('var', 1);
        }
        return container;
    },
    domToMutation: function (xmlElement) {
        this.hasVar_ = parseInt(xmlElement.getAttribute('var'), 10) == 1;
        this.updateShape_();
    },
    decompose: function (workspace) {
        var containerBlock = workspace.newBlock('sc_mth_mutator_container');
        containerBlock.initSvg();
        var connection = containerBlock.getInput('STACK').connection;
        if (this.hasVar_) {
            var varBlock = workspace.newBlock('sc_mth_mutator_var');
            varBlock.initSvg();
            connection.connect(varBlock.previousConnection);
        }
        return containerBlock;
    },
    compose: function (containerBlock) {
        var clauseBlock = containerBlock.getInputTargetBlock('STACK');
        this.hasVar_ = false;
        if (clauseBlock) {
            this.hasVar_ = true;
        }
        this.updateShape_();
    },
    saveConnections: function (containerBlock) {
        // No connections to save for simple field
    },
    updateShape_: function () {
        if (this.getInput('VAR_INPUT')) {
            this.removeInput('VAR_INPUT');
        }
        // Rebuild
        if (this.hasVar_) {
            this.appendDummyInput('VAR_INPUT')
                .appendField("Guardar em (%)")
                .appendField(new Blockly.FieldTextInput("nome_variavel"), "VAR_NAME");
        }
    }
};

Blockly.Extensions.registerMutator(
    'sc_mth_mutator',
    SC_MTH_MUTATOR_MIXIN,
    function () {
        this.hasVar_ = false;
        this.updateShape_();
    },
    ['sc_mth_mutator_var']
);
